export const FETCHING_DATA_START = 'FETCHING_DATA_START';
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS';
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE';

export const FETCHING_DRIVER_SCHEDULE_START = 'FETCHING_DRIVER_SCHEDULE_START';
export const FETCHING_DRIVER_SCHEDULE_SUCCESS = 'FETCHING_DRIVER_SCHEDULE_SUCCESS';
export const FETCHING_DRIVER_SCHEDULE_FAILURE = 'FETCHING_DRIVER_SCHEDULE_FAILURE';
